### ISSUE TITLE
Crash with Thermal Dynamics filter

### ISSUE THREAD

**Issue by dashkal16** [talonos2/BlightfallTracker#110]
The player who triggered it reports that he was trying to place a vanilla log into a Thermal Dynamics filter so as to stop a furnace from accepting wood logs.

```
[22:58:34] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
        at cofh.thermaldynamics.duct.item.SimulatedInv.setTarget(SimulatedInv.java:39) ~[SimulatedInv.class:?]
        at cofh.thermaldynamics.duct.item.SimulatedInv.wrapInv(SimulatedInv.java:14) ~[SimulatedInv.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.simTransfer(TileItemDuct.java:808) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.simTransferI(TileItemDuct.java:728) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.item.TileItemDuct.canRouteItem(TileItemDuct.java:700) ~[TileItemDuct.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.findRouteForItem(ServoItem.java:329) ~[ServoItem.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.getRouteForItem(ServoItem.java:419) ~[ServoItem.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.handleStuffedItems(ServoItem.java:298) ~[ServoItem.class:?]
        at cofh.thermaldynamics.duct.attachments.servo.ServoItem.tick(ServoItem.java:174) ~[ServoItem.class:?]
        at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:50) ~[ItemGrid.class:?]
        at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:62) ~[WorldGridList.class:?]
        at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:85) ~[TickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_420_TickHandler_tick_WorldTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by talonos2** [comment]
I spoke to the author and got this response:

 <skyboy>  if they're technically inclined dare them to trigger the crash
again, otherwise tell them they won't see it happen again even without an
update. the window in which you can trigger that error amounts to
nanoseconds

So... the question I guess is does this happen every time you load the
world? If so, does it have the same crash log every time?

**Comment by dashkal16** [comment]
Totally consistent.  I didn't start to worry until I got it again on reboot.  That stacktrace actually came from one of the reboots.

**Comment by JokarLP** [comment]
I have the same Problem with Fluiducts #114 it is every time the same crash log and every if i join on the position where i has place it

**Comment by talonos2** [comment]
I'm afraid this is out of our hands, and has already been reported to the mod author in question. I'll try updating Thermal Dynamics to the newest version. Hopefully that'll fix it.

**Comment by JokarLP** [comment]
It would fixed with the right Server Version for me
