### ISSUE TITLE
Commons-compress v 1.8.1 Download Failure

### ISSUE THREAD

**Issue by NetherBlade1** [talonos2/BlightfallTracker#133]
While attempting to download Blightfall's version 2.1.4. The mod commons-compress v 1.8.1 fails to download (copy fails) causing the mod-pack to be unable to launch (only  says install keeps failing to install), it always says that the copy-zip fails to copy. This occurs even after deleting and redownloading the pack, it also keeps happening after a full redownload of the Technic Launcher.

I am completely lost on how to upload the log, since Github refuses to allow anything but PNG GIF or JPG files to be uploaded. I could not find a trustworthy file converter or a trustworthy, customer service rating website to find out if the shadier converters were really scams or not.

So instead I added the section in which I believe the problem occurred below. Sorry about it not being formatted like it was in the log, I hope some sense can be made out of it.

Starting download of http://mirror.technicpack.net/Technic/mods/commons-compress/commons-compress-v1.8.1 - Copy.zip, with 1 tries remaining
[B#319] 2015/09/19 12:07:12 [SEVERE] java.net.SocketException: Unexpected end of file from server
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.http.HttpClient.parseHTTPHeader(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.http.HttpClient.parseHTTP(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at java.net.HttpURLConnection.getResponseCode(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.mirror.download.Download.run(Download.java:70)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.mirror.MirrorStore.downloadFile(MirrorStore.java:116)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.install.tasks.DownloadFileTask.runTask(DownloadFileTask.java:57)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.install.tasks.TaskGroup.runTask(TaskGroup.java:86)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.install.InstallTasksQueue.runAllTasks(InstallTasksQueue.java:52)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launchercore.install.ModpackInstaller.installPack(ModpackInstaller.java:42)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at net.technicpack.launcher.launch.Installer$1.run(Installer.java:116)
[B#319] 2015/09/19 12:07:12 [SEVERE]    at java.lang.Thread.run(Unknown Source)
[B#319] 2015/09/19 12:07:12 [SEVERE] Download of http://mirror.technicpack.net/Technic/mods/commons-compress/commons-compress-v1.8.1 - Copy.zip Failed!
[B#319] 2015/09/19 12:43:42 [INFO] Starting download of http://cdn.technicpack.net/platform2/pack-icons/592618.png?1442465351, with 3 tries remaining
[B#319] 2015/09/19 12:43:43 [WARNING] Unable to load platform pack m-cs-pack
net.technicpack.rest.RestfulAPIException: Error accessing URL [http://api.technicpack.net/modpack/m-cs-pack?build=319]
    at net.technicpack.rest.RestObject.getRestObject(RestObject.java:157)
    at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfo(HttpPlatformApi.java:57)
    at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfoForBulk(HttpPlatformApi.java:51)
    at net.technicpack.platform.cache.ModpackCachePlatformApi.pullAndCache(ModpackCachePlatformApi.java:132)
    at net.technicpack.platform.cache.ModpackCachePlatformApi.getPlatformPackInfoForBulk(ModpackCachePlatformApi.java:81)
    at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:58)
    at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
    at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
    at java.lang.Thread.run(Unknown Source)
Caused by: net.technicpack.rest.RestfulAPIException: Error in response: Modpack does not exist
    at net.technicpack.rest.RestObject.getRestObject(RestObject.java:146)
    ... 8 more
[B#319] 2015/09/19 12:43:43 [WARNING] Unable to load platform pack m-cs-pack
net.technicpack.rest.RestfulAPIException: Error accessing URL [http://api.technicpack.net/modpack/m-cs-pack?build=319]
    at net.technicpack.rest.RestObject.getRestObject(RestObject.java:157)
    at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfo(HttpPlatformApi.java:57)
    at net.technicpack.platform.http.HttpPlatformApi.getPlatformPackInfoForBulk(HttpPlatformApi.java:51)
    at net.technicpack.platform.cache.ModpackCachePlatformApi.pullAndCache(ModpackCachePlatformApi.java:132)
    at net.technicpack.platform.cache.ModpackCachePlatformApi.getPlatformPackInfoForBulk(ModpackCachePlatformApi.java:81)
    at net.technicpack.platform.PlatformPackInfoRepository.getPlatformPackInfo(PlatformPackInfoRepository.java:58)
    at net.technicpack.platform.PlatformPackInfoRepository.getPackInfo(PlatformPackInfoRepository.java:46)
    at net.technicpack.launchercore.modpacks.PackLoadJob$5.run(PackLoadJob.java:180)
    at java.lang.Thread.run(Unknown Source)
Caused by: net.technicpack.rest.RestfulAPIException: Error in response: Modpack does not exist
    at net.technicpack.rest.RestObject.getRestObject(RestObject.java:146)
    ... 8 more

**Comment by SelenaQuartzRose** [comment]
The best way to post crash logs here is to copy them into a site like www.pastebin.com and place a link here to the copied crash reports. There should be a copy of the report saved as a text file in /modpacks/blightfall/crash-reports folder.

**Comment by NetherBlade1** [comment]
I couldn't find a crashlog file in Blightfall (I think this is because the modpack didn't fully download due t the copy zip failure) however I did paste bin the log from the Technic Launcher log folder.

From: appdata/roaming/.technic/logs

http://pastebin.com/uMiRmxkA

**Comment by talonos2** [comment]
This seems to be a rare thing caused by the spaces in the file name. I'll fix it this coming version.
