### ISSUE TITLE
Automagy Tally Box Crash

### ISSUE THREAD

**Issue by Theginginator** [talonos2/BlightfallTracker#143]
I tried placing a whitelist in the automagy tally box and the game crashed. Any attempt at opening that world now causes a crash.

I'm not too familiar with crash logs, but I think that this is the relevant section. Any help is appreciated.
[B#319]  Description: Ticking block entity
[B#319]  
[B#319]  java.lang.ClassCastException: vazkii.botania.common.block.tile.TileSpecialFlower cannot be cast to tuhljin.automagy.tiles.IHasItemList
[B#319]     at tuhljin.automagy.tiles.TileEntityTally.getDetectedItems(TileEntityTally.java:46)
[B#319]     at tuhljin.automagy.tiles.TileEntityTallyBase.calculateRedstoneSignalStrength(TileEntityTallyBase.java:121)
[B#319]     at tuhljin.automagy.tiles.TileEntityTallyBase.func_145845_h(TileEntityTallyBase.java:109)
[B#319]     at net.minecraft.world.World.func_72939_s(World.java:1939)
[B#319]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[B#319]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[B#319]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[B#319]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[B#319]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[B#319]     at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[B#319]  
[B#319]  
[B#319]  A detailed walkthrough of the error, its code path and all known details is as follows:
[B#319]  ---------------------------------------------------------------------------------------
[B#319]  
[B#319]  -- Head --
[B#319]  Stacktrace:
[B#319]     at tuhljin.automagy.tiles.TileEntityTally.getDetectedItems(TileEntityTally.java:46)
[B#319]     at tuhljin.automagy.tiles.TileEntityTallyBase.calculateRedstoneSignalStrength(TileEntityTallyBase.java:121)
[B#319]     at tuhljin.automagy.tiles.TileEntityTallyBase.func_145845_h(TileEntityTallyBase.java:109)
[B#319]  
[B#319]  -- Block entity being ticked --
[B#319]  Details:
[B#319]     Name: tileEntityTally // tuhljin.automagy.tiles.TileEntityTally
[B#319]     Block type: ID #1815 (tile.blockTally // tuhljin.automagy.blocks.BlockTally)
[B#319]     Block data value: 2 / 0x2 / 0b0010
[B#319]     Block location: World: (565,63,1008), Chunk: (at 5,3,0 in 35,63; contains blocks 560,0,1008 to 575,255,1023), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
[B#319]     Actual block type: ID #1815 (tile.blockTally // tuhljin.automagy.blocks.BlockTally)
[B#319]     Actual block data value: 2 / 0x2 / 0b0010
[B#319]  Stacktrace:
[B#319]     at net.minecraft.world.World.func_72939_s(World.java:1939)
[B#319]     at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[B#319]

**Comment by omglolbah** [comment]
Looks like Automatgy is treating the flower as having an inventory, but it does not have one.
Removing the tally-box would probably fix your world.

I might be able to fix your world but I would need a copy of the minecraft/saves/<name of your world> folder to do so.
Throw me an email at blightfall@omglolbah.net if you need a way to push the file to me.
