### ISSUE TITLE
Kicked from server when attempting to scribe Dawn Machine research notes

### ISSUE THREAD

**Issue by LordQ42** [talonos2/BlightfallTracker#55]
multiplayer server,  when I attempt to scribe the research note for dawn machine it boots me out to the minecraft menu.

**Comment by dashkal16** [comment]
I have this as well.  There's a stacktrace in the server log including an NPE in the prior research tracker.
Will update when I'm able with the log.

**Comment by LordQ42** [comment]
as a side note, I was able to open a game in single player, obtain the dawn machine recipes, then copy my thaumcraft player data files up to my multiplayer server and it worked, not sure if that will help pin the issue down.

**Comment by dashkal16** [comment]
A little more information.

On login I get this error:
ERROR: Error loading DawnMachine.zs:
 stanhebben.zenscript.parser.TokenException: Invalid
 character at DawnMachine.zs:10 - ?
(That ? is in a white box.  Sadly, I can't copy-paste out to identify it)

Having a look at the file (copied from the server) nothing seems out of the ordinary.  I see the usual §l§1 color codes, but that's it.

And finally, here's the stacktrace:

```
[15:52:30] [Server thread/ERROR] [FML/]: There was a critical exception handling a packet on channel thaumcraft
java.lang.NullPointerException
        at thaumcraft.common.lib.research.ResearchManager.doesPlayerHaveRequisites(ResearchManager.java:517) ~[ResearchManager.class:?]
        at thaumcraft.common.lib.network.playerdata.PacketPlayerCompleteToServer.onMessage(PacketPlayerCompleteToServer.java:64) ~[PacketPlayerCompleteToServer.class:?]
        at thaumcraft.common.lib.network.playerdata.PacketPlayerCompleteToServer.onMessage(PacketPlayerCompleteToServer.java:20) ~[PacketPlayerCompleteToServer.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

```

**Comment by LordQ42** [comment]
So after all that, I was able to unlock the recipes by copying and pasting my thaumcraft player data from a single player to multiplayer server, I can see the recipe now, but when I attempt to use it at the arcane infuser it doesn't work. I tried it on my single player setup and it did. Same launcher, same version of blightfall, only difference was Single to Multiplayer. dunno what the issue is but it's gonna bug me.

**Comment by LordQ42** [comment]
further research, I went in to the dawnmachine.zs script on my server and deleted every instance of the curly character that causes the problem on some but not all machines. Now it works. The problem is almost definitely that non-standard character.

**Comment by dashkal16** [comment]
Interesting.  I wonder if it can be traced to a locale issue.

**Comment by talonos2** [comment]
It can be. It should be fixed now.
