### ISSUE TITLE
how to make a good working server??

### ISSUE THREAD

**Issue by DeBobbel** [talonos2/BlightfallTracker#84]
now 1 little question over, if i download the server.
make a folder, put everyting on it, confirm ealu etc, op the server, it work, butt it skips somethings
so i dont have quests i spawn random, i dont have the mods etc, i think its the ram for the server, could you please help. send a video or something else.

Bjornkok (if i do something wrong, explane it please)

**Comment by skittishtrigger** [comment]
the default setup works out of the box (I downloaded to test).  You need to provide logs from either logs/ in the root of the server or in crash-reports/. Without further info there is not much he can do.

**Comment by LordQ42** [comment]
I had a similar issue when setting up my server, it loaded without textures, dumped you in the ocean, etc... what I had to do was make sure I had a working version of technic and forge running on the server machine, basically run the single player on the server to test then open the server.

**Comment by DeBobbel** [comment]
so what i nee to do, is copy all my singleplayer world things into the server and start the server??

**Comment by mattcloward** [comment]
Most likely, you ran the incorrect file.  You have to run "start.bat" for the mods to work. If you run that and it says something about not having enough space for an object heap, edit the start.bat and change the 3 and 2 to 1 each. Hope that helps!

**Comment by TheJackano** [comment]
My server isn't working and I'm not sure how to fix it. Here's the Crash Report:

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 27/08/15 17:05
Description: Exception in server tick loop

java.lang.ClassCastException: com.pam.harvestcraft.BlockPamSapling cannot be cast to cofh.thermaldynamics.duct.BlockDuct
    at cofh.thermaldynamics.block.TileTDBase.getDuctType(TileTDBase.java:717)
    at cofh.thermaldynamics.duct.item.TileItemDuct.getPipeLength(TileItemDuct.java:368)
    at cofh.thermaldynamics.duct.item.TravelingItem.tickForward(TravelingItem.java:82)
    at cofh.thermaldynamics.duct.item.TileItemDuct.tickItems(TileItemDuct.java:417)
    at cofh.thermaldynamics.duct.item.TileItemDuct.tickPass(TileItemDuct.java:199)
    at cofh.thermaldynamics.duct.item.ItemGrid.tickGrid(ItemGrid.java:39)
    at cofh.thermaldynamics.core.WorldGridList.tickEnd(WorldGridList.java:62)
    at cofh.thermaldynamics.core.TickHandler.tick(TickHandler.java:85)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_419_TickHandler_tick_WorldTickEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
    at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:255)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:645)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1492410328 bytes (1423 MB) / 2568486912 bytes (2449 MB) up to 2863661056 bytes (2731 MB)
    JVM Flags: 3 total; -Xmx3G -Xms2G -XX:MaxPermSize=128m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 1, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1291 Minecraft Forge 10.13.2.1291 101 mods loaded, 101 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1291} [Forge Mod Loader](Blightfall.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1291} [Minecraft Forge](Blightfall.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv2-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    blightcore{1.2.0} [Blight Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.3} [MobiusCore](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    newradicalbotany{1.1.2} [New Radical Botany](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.4.83} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.83-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    notimefix{2.1.0} [No Time Fix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PlayerAPI{1.4} [Player API](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AppleCore{1.1.0} [AppleCore](AppleCore-mc1.7.10-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv2-stable-1} [Applied Energistics 2](appliedenergistics2-rv2-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships](ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-268.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Automagy{0.24.1} [Automagy](Automagy-1.7.10-0.24.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterrain{0.15} [Better Rain](betterrain-1.7.2-1.7.10_0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    betterstorage{0.13.1.126} [BetterStorage](BetterStorage-1.7.10-0.13.1.126.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.10.3} [BiblioCraft](BiblioCraft[v1.10.3][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins186} [Mantle](Mantle-1.7.10-0.3.2.jenkins186.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Natura{2.2.0} [Natura](natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioWoodsNatura{1.4} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0-81.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.1-182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.4.1A2} [Big Reactors](BigReactors-0.4.1A2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AWWayofTime{v1.3.0a} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.0a-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.6-191} [Botania](Botania r1.6-191.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ChickenChunks{1.3.4.16} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.16-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cookingbook{1.0.0} [Cooking for Blockheads](cookingbook-mc1.7.10-1.0.54-mt3hack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    customnpcs{1.7.10c} [CustomNpcs](CustomNPCs-1.7..10c-herohack2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderStorage{1.4.5.24} [EnderStorage](EnderStorage-1.7.10-1.4.5.24-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMultipart{1.1.1.321} [Forge Multipart](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.5} [Extra Utilities](extrautilities-1.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.3-RFNerf.DEV.1911337} [Tinkers' Construct](TConstruct-1.7.10-1.8.3-RFNerf.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy{4.0.5} [Metallurgy 4](Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    harvestcraft{1.7.10g} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10h.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-471.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForbiddenMagic{1.7.10-0.562} [Forbidden Magic](Forbidden Magic-1.7.10-0.562.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HelpFixer{1.0.7} [HelpFixer](HelpFixer-1.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreQuesting{The Journey (4.2.3)} [Hardcore Questing Mode](HQM-The Journey %284.2.3%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inpure|core{1.7.10R1.0.0B9} [INpureCore](INpureCore-[1.7.10]1.0.0B9-62.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    JABBA{1.1.4} [JABBA](Jabba-1.1.4_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    LunatriusCore{1.1.2.21} [LunatriusCore](LunatriusCore-1.7.10-1.1.2.21-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0-104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modelcitizens{1.0.1} [Model Citizens](ModelCitizens-mc1.7.10-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    modtweaker2{0.7} [Mod Tweaker 2](ModTweaker 2-0.7.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Netherless{0.9.0} [Netherless](Netherless-0.9.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NetherOres{1.7.10R2.3.0RC4} [Nether Ores](NetherOres-[1.7.10]2.3.0RC4-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PerfectSpawn{1.1} [Perfect Spawn](PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    purplepanic{1.0.1} [Purple Panic](purplepanic-1.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RedstoneArsenal{1.7.10R1.1.0} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0-80.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    biomescanner{0.1.0} [Biome Scanner](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    blightbuster{0.1.0} [BlightBuster](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    cavestokingdoms{0.0.1} [Caves to Kingdoms](reqcredit-1.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RPGAdvMod{1.0.0} [RPGAdvMod](RPGAdvMod-1.0.0_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Schematica{1.7.5.git} [Schematica](Schematica-1.7.10-1.7.5-GenHack2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SpiceOfLife{1.2.4} [The Spice of Life](SpiceOfLife-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    StorageDrawers{1.7.10-1.5.3} [Storage Drawers](StorageDrawers-1.7.10-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TabulaRasa{1.7.10R1.0.1} [Tabula Rasa](TabulaRasa-[1.7.10]1.0.1-3-Blight3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    playerzombiemod{v1} [Tainted Players](TaintedPlayers-v1-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TerrainControl{2.7.0-SNAPSHOT} [Terrain Control](terraincontrol-forge-2.7.0-colored-lockhack.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    thaumcraftneiplugin{1.7.10-1.7} [Thaumcraft NEI Plugin](thaumcraftneiplugin-1.7.10-1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    thaumicenergistics{0.8.10.6} [Thaumic Energistics](thaumicenergistics-0.8.10.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalDynamics{1.7.10R1.0.0RC7} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.0.0RC7-98.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.2.4} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TMechworks{1.7.10-67.34d1d9b} [Tinkers' Mechworks](TMechworks_mc1.7.10_0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TML{3.0.1} [TooMuchLoot](TooMuchLoot-1.7.10-3.0.1.B22-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Translocator{1.1.1.12} [Translocator](Translocator-1.7.10-1.1.1.12-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    UndergroundBiomes{0.7} [Underground Biomes Constructs](UndergroundBiomesConstructs-1.7.2-test41.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ubcores{1.7.10-0.1.2.0} [UBC Ore Registrar](UBCOres-1.7.10-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    McMultipart{1.1.1.321} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HungerOverhaul{1.7.10-1.0.0.DEV.c9b8cee} [Hunger Overhaul](HungerOverhaul-1.7.10-1.0.0-ConfigHack-2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.1.4.DEV.0edeedd} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.4.DEV.0edeedd.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ForgeMicroblock{1.1.1.321} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.1.321-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: stable rv2-stable-1 for Forge 10.13.2.1291
    CoFHCore: -[1.7.10]3.0.2-268
    MineFactoryReloaded: -[1.7.10]2.8.0-104
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.0.0-81
    ThermalExpansion: -[1.7.10]4.0.1-182
    TConstruct Environment: Environment healthy.
    NetherOres: Lacking version information.
    RedstoneArsenal: -[1.7.10]1.1.0-80
    ThermalDynamics: -[1.7.10]1.0.0RC7-98
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:ON
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 0 / 20; []
    Is Modded: Definitely; Server brand changed to 'fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by sheawild** [comment]
Do me a faviour and post the text in of your start.bat file because im confused and on a mac my server isnt working

**Comment by mattcloward** [comment]
This is the contents of my start.bat:
java -Xmx1G -Xms1G -XX:MaxPermSize=128m -jar "Blightfall.jar" nogui
pause

I edited the amount of memory allocated to 1G in both places, where originally it was 3G and 2G.

**Comment by sheawild** [comment]
Are u using a mac or pc

**Comment by mattcloward** [comment]
I'm using a PC. I'm not sure if there is a difference. Can you run the .bat file? Is there an error log?

**Comment by sheawild** [comment]
No you cannot run a .bat on a mac _whiny voice_ its so unfair

**Comment by sheawild** [comment]
Could you plz post your whole server file on dropbox ect and share it with me plz

**Comment by mattcloward** [comment]
I'll see what I can do when I get home. I am at work. Thanks for your patience. For now, just run the forge.jar. That should work.

**Comment by sheawild** [comment]
Forge.jar in the mods folder?

**Comment by sheawild** [comment]
this is my crash report

**Comment by mattcloward** [comment]
I apologize, the forge.jar is actually named "Blightfall.jar". It is in the main server folder. Try to run that. If it doesn't work, let us know.

**Comment by sheawild** [comment]
Oh i allreby did that
Is says starting server
Then unloading dimension17
1
100
4

**Comment by mattcloward** [comment]
Okay, I did some research (I apologize for not doing so earlier) and found a tutorial for setting up a server for OS X on Minecraft Wiki [here](http://minecraft.gamepedia.com/Setting_up_a_server#Configuring_the_Minecraft_server).

Watch the first video under OS X on how to do it. You have to create the start.command with TextEdit (be sure to format to plain text), place it in your server folder, and configure the terminal. Unfortunately, I'm going to have to open a new issue because I get a crash report when trying to run the start.command.

This is more difficult than I thought, but we should be able to work it out!

**Comment by sheawild** [comment]
Do you reckon its just lake a normal minecraft server
thank you so much for doing the reserch i was trying to work off past knowlage of the subject

**Comment by sheawild** [comment]
'FALCEPALM' i didnt activate my portforwarding

**Comment by mattcloward** [comment]
Does it work now? :)

**Comment by sheawild** [comment]
yes thankyou for all of your help

**Comment by sheawild** [comment]
nope worlds dead :-( 
cannot log on on single player instantly crashes every time
